function currentFinancialYearCode(date = new Date()) {
  const startYear = date.getMonth() >= 3 ? date.getFullYear() : date.getFullYear() - 1;
  return `${String(startYear).slice(-2)}${String(startYear + 1).slice(-2)}`;
}

export const DEFAULT_SETTINGS = {
  shop_name: 'Wash Nest',
  shop_phone: '',
  shop_address: '',
  gst_number: '',
  gst_enabled: 'false',
  gst_rate: '18',
  express_multiplier: '1.5',
  default_delivery_charge: '0',
  next_order_number: '1',
  financial_year: currentFinancialYearCode(),
};

const PRICE_ROWS = [
  ['wash_fold', 'Shirt', 'clothing', 20, null, false],
  ['wash_fold', 'T-Shirt', 'clothing', 20, null, false],
  ['wash_fold', 'Trousers', 'clothing', 25, null, false],
  ['wash_fold', 'Jeans', 'clothing', 30, null, false],
  ['wash_fold', 'Shorts', 'clothing', 15, null, false],
  ['wash_fold', 'Kurta', 'clothing', 25, null, false],
  ['wash_fold', 'Kurta Set', 'clothing', 40, null, false],
  ['wash_fold', 'Saree', 'clothing', 50, null, false],
  ['wash_fold', 'Salwar Kameez', 'clothing', 40, null, false],
  ['wash_fold', 'Jacket', 'clothing', 50, null, false],
  ['wash_fold', 'Sweater', 'clothing', 40, null, false],
  ['wash_fold', 'Hoodie', 'clothing', 40, null, false],
  ['wash_fold', 'Innerwear (per pc)', 'clothing', 10, null, false],
  ['wash_fold', 'Socks (pair)', 'clothing', 10, null, false],
  ['wash_fold', 'Bedsheet (Single)', 'bedding', 40, null, false],
  ['wash_fold', 'Bedsheet (Double)', 'bedding', 60, null, false],
  ['wash_fold', 'Pillow Cover', 'bedding', 15, null, false],
  ['wash_fold', 'Blanket (Single)', 'bedding', 100, null, false],
  ['wash_fold', 'Blanket (Double)', 'bedding', 150, null, false],
  ['wash_fold', 'Comforter', 'bedding', 200, null, false],
  ['wash_fold', 'Curtain (per piece)', 'household', 60, null, false],
  ['wash_fold', 'Towel (Small)', 'household', 15, null, false],
  ['wash_fold', 'Towel (Large/Bath)', 'household', 25, null, false],
  ['wash_fold', 'Table Cloth', 'household', 30, null, false],
  ['wash_fold', 'Sofa Cover', 'household', 80, null, false],
  ['wash_fold', 'Mixed Clothes (per kg)', 'clothing', 0, 49, true],
  ['iron', 'Shirt', 'clothing', 10, null, false],
  ['iron', 'T-Shirt', 'clothing', 10, null, false],
  ['iron', 'Trousers', 'clothing', 15, null, false],
  ['iron', 'Jeans', 'clothing', 15, null, false],
  ['iron', 'Kurta', 'clothing', 15, null, false],
  ['iron', 'Saree', 'clothing', 30, null, false],
  ['iron', 'Salwar Kameez', 'clothing', 25, null, false],
  ['iron', 'Suit (2-piece)', 'clothing', 50, null, false],
  ['iron', 'Suit (3-piece)', 'clothing', 70, null, false],
  ['iron', 'Bedsheet (Single)', 'bedding', 15, null, false],
  ['iron', 'Bedsheet (Double)', 'bedding', 25, null, false],
  ['wash_iron', 'Shirt', 'clothing', 30, null, false],
  ['wash_iron', 'T-Shirt', 'clothing', 30, null, false],
  ['wash_iron', 'Trousers', 'clothing', 35, null, false],
  ['wash_iron', 'Jeans', 'clothing', 40, null, false],
  ['wash_iron', 'Kurta', 'clothing', 35, null, false],
  ['wash_iron', 'Saree', 'clothing', 70, null, false],
  ['wash_iron', 'Salwar Kameez', 'clothing', 60, null, false],
  ['wash_iron', 'Suit (2-piece)', 'clothing', 120, null, false],
  ['wash_iron', 'Bedsheet (Single)', 'bedding', 50, null, false],
  ['wash_iron', 'Bedsheet (Double)', 'bedding', 80, null, false],
  ['dry_clean', 'Suit (2-piece)', 'clothing', 250, null, false],
  ['dry_clean', 'Suit (3-piece)', 'clothing', 350, null, false],
  ['dry_clean', 'Blazer', 'clothing', 200, null, false],
  ['dry_clean', 'Jacket/Coat', 'clothing', 250, null, false],
  ['dry_clean', 'Saree (Silk)', 'clothing', 200, null, false],
  ['dry_clean', 'Lehenga', 'clothing', 400, null, false],
  ['dry_clean', 'Sherwani', 'clothing', 350, null, false],
  ['dry_clean', 'Wedding Dress', 'clothing', 500, null, false],
  ['dry_clean', 'Blanket', 'bedding', 300, null, false],
  ['dry_clean', 'Curtain (per piece)', 'household', 150, null, false],
];

export const DEFAULT_PRICES = PRICE_ROWS.map((row, index) => ({
  id: index + 1,
  service_type: row[0],
  item_name: row[1],
  category: row[2],
  price: row[3],
  price_per_kg: row[4],
  is_per_kg: row[5],
  active: true,
}));